config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :chats


 get '/home',   to: 'welcome#index',    as: 'home'
 get '/login',  to: 'sesssions#new',    as: 'login'
 post '/login', to: 'sesssions#create', as: 'create_session'
 get '/about',  to: 'welcome#about',    as: 'about'
 get '/logout', to: 'sesssions#destroy', as: 'logout'

 root 'chats#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :chats, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user


  def authenticate_user
    unless user_logged_in?
      flash[:alert] = "You must be logged in to do that."
      redirect_to login_path
    end
  end

  def current_user
    if user_logged_in?
    User.find(session[:logged_in_user_id])
    end
  end
  helper_method :current_user

  def user_logged_in?
    session[:logged_in_user_id].present?
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.last(5)
    @chat = Chat.new
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new

  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)
    @chat.user_id = current_user.id

    respond_to do |format|
      if @chat.save
        format.html { redirect_to chats_path, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:messages, :user_id)
    end
end

app/controllers/sesssions_controller.rb
class SesssionsController < ApplicationController
  skip_before_filter :authenticate_user

  def new #login page
  end

  def about
  end

  def create #a session
    user = User.find_by_username(params[:username])
    if user.present? && user.authenticate(params[:password])
      set_user_session(user)
      redirect_to chats_path, notice: "Log in successful."
    else
      render :new
      flash[:alert] = "Username or password did not match."
    end
  end

  def destroy #logout
    session[:logged_in_user_id] = nil
    redirect_to home_path, notice: "You have logged out."
  end

  private

  def set_user_session(user)
    session[:logged_in_user_id] = user.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user, only: [:new, :create]
  # # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
skip_before_filter :authenticate_user, only: [:index, :about]

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/sesssions_helper.rb
module SesssionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Type your chat message here; field cannot be empty" %><br>
    <%= f.text_field :messages %>
  </div>
  <div class="actions">
    <button class="btn waves-effect waves-light" id='newMessage'>Submit</button>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<h5>Leave a message in our chatroom</h5>
<div class="chat-window" style="border:1px solid black">
  <table class='centered'>
    <thead>
      <tr>
        <th>Messages</th>
        <th>User</th>
        <th>Time posted</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="chat-reload">
      <% @chats.each do |chat| %>
        <tr>
          <td><%= chat.messages %></td>
          <td><%= chat.user.username %></td>
          <td><%= chat.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <%= render 'form' %>
</div>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p>
  <strong>Messages:</strong>
  <%= @chat.messages %>
</p>

<p>
  <strong>User:</strong>
  <%= @chat.user.username %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <div class="container" style="border:1px solid black">
    <body>
      <%= react_component("Navigation") %>
      <div class='container'>
        <div class='row'>
          <div class='m12'>
            <%= yield %>
          </div>
        </div>
      </div>
    </body>
  </div>

  <footer>
    <%= "User logged in: #{current_user.username}" if current_user %>
  </footer>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</html>

app/views/sesssions/_form.html.erb
<%= form_tag login_path do %>

  <div class="field">
    <%= label_tag :username %><br>
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>

    <%= submit_tag "Submit" %><br>
    
    <button name="button"><%= link_to('Create new account', new_user_path) %></button>
<% end %>

app/views/sesssions/create.html.erb
<h1>Sesssions#create</h1>
<p>Find me in app/views/sesssions/create.html.erb</p>

app/views/sesssions/destroy.html.erb
<h1>Sesssions#destroy</h1>
<p>Find me in app/views/sesssions/destroy.html.erb</p>

app/views/sesssions/index.html.erb
<h1>Sesssions#index</h1>
<p>Find me in app/views/sesssions/index.html.erb</p>

app/views/sesssions/new.html.erb
<h2> Login page </h2>
<%= render 'form' %>

app/views/sesssions/show.html.erb
<h1>Sesssions#show</h1>
<p>Find me in app/views/sesssions/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<!--
<p>
  <%# @user.chat.messages %>
</p> -->

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<h1 id="toc_0">About us:</h1>

<h2 id="toc_1">Welcome to Scary Chat!</h2>

<p>We are a couple wild and crazy students working our way through The Iron Yard coding school. We don&#39;t have any spare time so I couldn&#39;t tell you what we do for fun and entertainment. Because we are in the backend course we focus on Ruby, Rails and some javascript. Our styling leaves people in tears, not because it&#39;s so good, but because it&#39;s that bad.</p>

<p>Michelle is the CEO. She has been running chat apps for a little over 26hrs. In such a short time she has really made a name for herself. taking blank Atom page and turning it into a fully functioning app.</p>

<p>Chris is the CIO. He has been doing chat apps for going on a week. He bring wild ideas and novel concepts to the table. Chris&#39; flare for the adventures is what lead them down this monstorous path.</p>

app/views/welcome/index.html.erb
<div class = 'home'>
  <h1>Welcome to our chat app!</h1>
  <img src="http://www.mrwallpaper.com/wallpapers/3d-cute-monster-1280x800.jpg">
  <p>Chat app for monsters</p>
</div>